---

- name: Install x509_certs_packages
  pkgng:
    name: "{{ item }}"
    state: present
  with_items: "{{ x509_certs_packages }}"

- name: Install x509_certs_additional_packages
  pkgng:
    name: "{{ item }}"
    state: present
  with_items: "{{ x509_certs_additional_packages }}"
